services:
  postgres:
    image: postgres:15-alpine
    container_name: zv_postgres
    environment:
      POSTGRES_DB: zvezdnoe_vereteno
      POSTGRES_USER: zv_user
      POSTGRES_PASSWORD: zv_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zv_user -d zvezdnoe_vereteno"]
      interval: 10s
      timeout: 5s
      retries: 5

  

  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: zv_minio
    environment:
      MINIO_ROOT_USER: zv_admin
      MINIO_ROOT_PASSWORD: zv_admin_password
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data:
